<?php

/*
 *
 *  __  __                        _
 * |  \/  | __ _ _   _ _   _ _ __(_)
 * | |\/| |/ _` | | | | | | | '__| |
 * | |  | | (_| | |_| | |_| | |  | |
 * |_|  |_|\__,_|\__, |\__,_|_|  |_|
 *               |___/
 *
 * Copyright (c) 2022-2023 Mayuri and contributors
 *
 * Permission is hereby granted to any persons and/or organizations
 * using this software to copy, modify, merge, publish, and distribute it.
 * Said persons and/or organizations are not allowed to use the software or
 * any derivatives of the work for commercial use or any other means to generate
 * income, nor are they allowed to claim this software as their own.
 *
 * The persons and/or organizations are also disallowed from sub-licensing
 * and/or trademarking this software without explicit permission from Mayuri.
 *
 * Any persons and/or organizations using this software must disclose their
 * source code and have it publicly available, include this license,
 * provide sufficient credit to the original authors of the project (IE: Mayuri),
 * as well as provide a link to the original project.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,FITNESS FOR A PARTICULAR
 * PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
 * USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * @author Mayuri
 *
 */

declare(strict_types=1);

namespace mayuri\form\elements\components;

use mayuri\form\elements\Element;
use pocketmine\form\FormValidationException;

class Dropdown extends Element {
	/** @var string[]|array */
	protected array $options;
	/** @var int */
	protected int $default;

	public function __construct(string $text, array $options, int $default = 0) {
		parent::__construct($text);
		$this->options = array_values($options);
		$this->default = $default;
	}

	public function getOptions(): array {
		return $this->options;
	}

	public function getSelectedOption(): string {
		return $this->options[$this->value];
	}

	public function getDefault(): int {
		return $this->default;
	}

	public function getType(): string {
		return "\x64\x72\x6f\x70\x64\x6f\x77\x6e";
	}

	public function serializeElementData(): array {
		return ["\x6f\x70\x74\x69\x6f\x6e\x73" => $this->options, "\x64\x65\x66\x61\x75\x6c\x74" => $this->default];
	}

	public function validate(mixed $value): void {
		parent::validate($value); // TODO: Change the autogenerated stub
		if (!isset($this->options[$value])) {
			throw new FormValidationException("\x4f\x70\x74\x69\x6f\x6e\x20\x77\x69\x74\x68\x20\x69\x6e\x64\x65\x78\x20" . $value . "\x20\x64\x6f\x65\x73\x20\x6e\x6f\x74\x20\x65\x78\x69\x73\x74\x20\x69\x6e\x20\x64\x72\x6f\x70\x64\x6f\x77\x6e");
		}
	}
}